library(lubridate)
library(dplyr)
Sys.setlocale("LC_ALL","English")
hpc_long<-read.csv2("household_power_consumption.txt")
hpc=rbind(hpc_long[grep("^1/2/2007",hpc_long$Date),],hpc_long[grep("^2/2/2007",hpc_long$Date),])
hpc$Global_active_power=as.numeric(as.character(hpc$Global_active_power))
hpc$Date<-as.character(hpc$Date)
hpc$Time<-as.character(hpc$Time)
hpc=mutate(hpc, date_time = paste(Date, Time, sep = " "))
hpc$date_time = dmy_hms(hpc$date_time)
plot(hpc$date_time,hpc$Global_active_power,type = "n", xlab = "", ylab = "Global Active Power (kilowatts)")
lines(hpc$date_time,hpc$Global_active_power)
dev.copy(png,file = "plot2.png", height = 480, width = 480, units = "px")
dev.off()
